-- Migration 007: Partner Simulations
-- Tracks every link generated by a partner in the portal.
-- Status moves from 'pending' → 'converted' when the client submits their quote.

CREATE TABLE IF NOT EXISTS partner_simulations (
  id                        UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  partner_id                UUID         REFERENCES partners(id) ON DELETE SET NULL,
  coupon_code               TEXT,
  partner_name              TEXT,
  spaces                    JSONB        NOT NULL DEFAULT '[]',
  total_plates              INT,
  total_area_m2             NUMERIC(10,2),
  material_total            INT,
  material_discounted       INT,
  sim_url                   TEXT,
  status                    TEXT         NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','converted')),
  converted_at              TIMESTAMPTZ,
  client_email_sequence_id  UUID         REFERENCES client_email_sequences(id) ON DELETE SET NULL,
  created_at                TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS partner_simulations_partner_id_idx ON partner_simulations(partner_id);
CREATE INDEX IF NOT EXISTS partner_simulations_status_idx     ON partner_simulations(status);
CREATE INDEX IF NOT EXISTS partner_simulations_created_at_idx ON partner_simulations(created_at DESC);
