-- Migration 018: Visualizador renders — capture, notify, surface in admin
--
-- When a client uses the Visualizador (AI applies a panel to their photo) and
-- then clicks "Prosseguir para o simulador", the generated render(s) are saved
-- so they can be (a) e-mailed + WhatsApp'd to the client and the Orbital team
-- when the orçamento is submitted, and (b) shown in the admin Clientes tab.
--
-- The image files themselves live in the public `site-images` storage bucket
-- under `visualizador-renders/<id>/<n>.png`; this table only stores the public
-- URLs + light metadata. All access is server-side via the service role.

-- One row per Visualizador → Simulador handoff. `id` is generated by the
-- save-render endpoint and carried forward on the Simulador URL (?viz_render=).
CREATE TABLE IF NOT EXISTS visualizador_renders (
  id          UUID PRIMARY KEY,
  -- Array of { url, local, productName, productCode }.
  images      JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Renders attached to a submitted orçamento, so the Clientes tab can show them
-- inline. Same { url, local, productName, productCode } shape as above.
ALTER TABLE client_email_sequences
  ADD COLUMN IF NOT EXISTS render_images JSONB;
