-- Migration 019: Rep portal — agenda + own CRM for partners
--
-- Sales reps could only see commission history and a flat partner list. This
-- adds two things reps asked for: a meeting agenda, and a pipeline CRM over
-- the partners they're in contact with (mirrors the admin Leads CRM from
-- migration 015 — same activity-timeline and reminder-recurrence shape).
--
--   rep_meetings      the agenda. One row per meeting. `partner_id` is
--                     nullable — a rep can book a meeting unconnected to any
--                     tracked partner. `invitees` is free-text JSON
--                     ({name, phone, email}) since the portal has no
--                     multi-user accounts to link against.
--
--   rep_partner_crm   one row per (rep, partner) relationship — the pipeline
--                     state: contact/meeting dates, whether the sample kit
--                     ("mostruário") went out, whether the partner has
--                     specified Orbital in a client project, follow-up and
--                     reminder fields (same shape as leads.next_reminder_at /
--                     reminder_note / reminder_recur / reminder_sent_at from
--                     migrations 012 + 016).
--
--                     Revenue/projects generated by the partner is NOT stored
--                     here — it's computed live from coupon_uses by the
--                     partner's coupon_code, same as
--                     /api/representante/partners already does.
--
--   rep_partner_notes the activity timeline, structurally identical to
--                     lead_notes (migration 015).

-- ── Agenda ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rep_meetings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_rep_id UUID NOT NULL REFERENCES sales_reps(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES partners(id) ON DELETE SET NULL,

  title TEXT NOT NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  duration_minutes INT NOT NULL DEFAULT 60,
  location TEXT,
  notes TEXT,
  invitees JSONB NOT NULL DEFAULT '[]',

  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'completed', 'cancelled')),

  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rep_meetings_rep_id ON rep_meetings (sales_rep_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_rep_meetings_partner_id ON rep_meetings (partner_id);

ALTER TABLE rep_meetings ENABLE ROW LEVEL SECURITY;

-- ── Rep's own partner CRM ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rep_partner_crm (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_rep_id UUID NOT NULL REFERENCES sales_reps(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES partners(id) ON DELETE CASCADE,

  stage TEXT NOT NULL DEFAULT 'novo_contato'
    CHECK (stage IN ('novo_contato', 'reuniao_agendada', 'reuniao_realizada', 'acompanhamento', 'ativo', 'inativo')),

  first_contact_at TIMESTAMPTZ,
  meeting_id UUID REFERENCES rep_meetings(id) ON DELETE SET NULL,
  meeting_happened_at TIMESTAMPTZ,

  mostruario_sent BOOLEAN NOT NULL DEFAULT false,
  mostruario_sent_at TIMESTAMPTZ,

  has_specified BOOLEAN NOT NULL DEFAULT false,
  last_specified_at TIMESTAMPTZ,

  last_followup_at TIMESTAMPTZ,

  next_reminder_at TIMESTAMPTZ,
  reminder_note TEXT,
  reminder_recur TEXT NOT NULL DEFAULT 'none'
    CHECK (reminder_recur IN ('none', 'daily', 'weekly', 'monthly')),
  reminder_sent_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  UNIQUE (sales_rep_id, partner_id)
);

CREATE INDEX IF NOT EXISTS idx_rep_partner_crm_rep_id ON rep_partner_crm (sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_rep_partner_crm_reminder ON rep_partner_crm (next_reminder_at);

ALTER TABLE rep_partner_crm ENABLE ROW LEVEL SECURITY;

-- ── Activity timeline ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rep_partner_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  crm_id UUID NOT NULL REFERENCES rep_partner_crm(id) ON DELETE CASCADE,

  kind TEXT NOT NULL DEFAULT 'note'
    CHECK (kind IN ('note', 'call', 'message', 'meeting', 'followup', 'system')),

  body TEXT NOT NULL,
  author TEXT,

  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rep_partner_notes_crm_id ON rep_partner_notes (crm_id, created_at DESC);

ALTER TABLE rep_partner_notes ENABLE ROW LEVEL SECURITY;
